### ISSUE TITLE
Installation on a edx server

### ISSUE THREAD

**Issue by DanielZuwala** [openfun/fun-apps#208]
Hi,

I have installed a fullstack EDX on a ubuntu 12.04 server. I now wonder how I could installed openFun on this already functional installation. Do I simply need to clone this repo on my /edx/app/edxapp folder, or do I need something more ?

**Comment by regisb** [comment]
The best way to start with FUN is to use a VM: https://github.com/openfun/fun-boxes
We provide packaged instances for VirtualBox and the latest available version is 2.17.2. If you wish to deploy FUN on your own server, I suggest you take a look at the upgrade playbook https://github.com/openfun/fun-boxes/blob/master/releases/upgrade.yml
