### ISSUE TITLE
Courses Facets

### ISSUE THREAD

**Issue by cloudy1** [openfun/fun-apps#579]
How did you manage to create courses facets like this ?

![selection_003](https://cloud.githubusercontent.com/assets/23309890/20053229/44f209b6-a4e0-11e6-9880-80bb2ed6e4be.png)

I searched in openedx documentation but had no luck.

**Comment by rmoch** [comment]
Hi

We created an application to store our metadata about courses, which are then indexed in elasticsearch, the user interface is a Backbone application.
you can see there:
https://github.com/openfun/fun-apps/blob/dev/courses/models.py
https://github.com/openfun/fun-apps/blob/dev/courses/management/commands/update_courses.py
https://github.com/openfun/fun-apps/tree/dev/courses_api
https://github.com/openfun/fun-apps/blob/dev/course_pages/templates/course_pages/index.html

But edX introduced such a feature in Dogwood, with the `course_overview` application.

**Comment by cloudy1** [comment]
Thanks @rmoch for your fast reply.
Also I am sorry to open issue before I read the code.

**Comment by cloudy1** [comment]
@rmoch I managed to add new fields to course_overview but now I need to index them in elasticsearch.

can you help me with link or post ?

**Comment by rmoch** [comment]
Not much.
You should ask such question to edX.
You can edX's Slack here http://openedx-slack-invite.herokuapp.com/

**Comment by cloudy1** [comment]
Thanks again @rmoch .
