### ISSUE TITLE
How to integrate with fun-platform

### ISSUE THREAD

**Issue by dnna** [openfun/fun-apps#641]
Hello,

I have successfully installed and ran https://github.com/openfun/fun-platform , but I'm unsure how to install fun apps on it. I tried running

``
pip install --extra-index-url https://pypi.fury.io/openfun fun-apps
``

in the lms-dev shell, but I see no changes - I see the default edx theme and no fun functionalities.

Do I need to modify any config files in order to activate it? Is there any setup guide for it?

**Comment by rmoch** [comment]
Hi
`fun-apps` code is not yet ported to recent version of `edx-platform` and may never be. 
So assuming your are working on `master` branch of `fun-platform`, it's not possible.
The only version where both code base work fine is Dogwood, you can get it running by checkouting `dogwood-funmooc` branch of `fun-platform` and rebuilding everything.

**Comment by dnna** [comment]
@rmoch I see, thank you for the response. I will try dogwood-funmooc as suggested.
If I may suggest, I think it would be useful to write this in the fun-apps or fun-platform readme in case someone else tries to set it up from master :)
