### ISSUE TITLE
Change css.fun .plan h2 

### ISSUE THREAD

**Issue by hugolpz** [openfun/fun-apps#647]
Dark title on dark blue results in poor contrast, poor style; poor readability. White gives better results.

https://github.com/openfun/fun-apps/blob/010a32bb03d4a236f5432869d417a8ad5786b9ab/funsite/static/funsite/css/fun.css#L1933

```
  .course-about .description section.plan h2 {
        color: black;
        margin-top: 20px;
        margin-bottom: 40px;
    }
```
into 

```
    .course-about .description section.plan h2 {
        margin-top: 20px;
        margin-bottom: 40px;
    }
```

![screenshot from 2019-03-04 17-25-12](https://user-images.githubusercontent.com/1420189/53746954-88aa5880-3ea2-11e9-86dd-eee50df4d1ec.png)

![screenshot from 2019-03-04 17-25-24](https://user-images.githubusercontent.com/1420189/53746953-88aa5880-3ea2-11e9-8e0d-58c1b54f83f5.png)

**Comment by jmaupetit** [comment]
Hi @hugolpz! Thanks for the report. I have to admit that your remark makes sense. We'll discuss about this internally and get back to you soon.

**Comment by hugolpz** [comment]
Woow. Super speed. I take notes of it :dancer:

**Comment by rmoch** [comment]
thanks @hugolpz , its online.
